/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddCollectionPolicy
 * @category generated
 */
export type AddCollectionPolicyInstructionArgs = {
  communityIdx: number
  collectionIdx: number
  rate: beet.bignum
  epoch: beet.bignum
  minimumStakeTime: beet.bignum
  interactionFrequency: beet.bignum
  attenuation: number
  permanentPolicy: boolean
  timeCapped: beet.bignum
}
/**
 * @category Instructions
 * @category AddCollectionPolicy
 * @category generated
 */
export const addCollectionPolicyStruct = new beet.BeetArgsStruct<
  AddCollectionPolicyInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['communityIdx', beet.u32],
    ['collectionIdx', beet.u32],
    ['rate', beet.u64],
    ['epoch', beet.i64],
    ['minimumStakeTime', beet.i64],
    ['interactionFrequency', beet.i64],
    ['attenuation', beet.u32],
    ['permanentPolicy', beet.bool],
    ['timeCapped', beet.i64],
  ],
  'AddCollectionPolicyInstructionArgs'
)
/**
 * Accounts required by the _addCollectionPolicy_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] communityPool
 * @property [_writable_] collection
 * @property [_writable_] collectionPolicy
 * @property [_writable_] mainPool
 * @category Instructions
 * @category AddCollectionPolicy
 * @category generated
 */
export type AddCollectionPolicyInstructionAccounts = {
  admin: web3.PublicKey
  communityPool: web3.PublicKey
  collection: web3.PublicKey
  collectionPolicy: web3.PublicKey
  mainPool: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addCollectionPolicyInstructionDiscriminator = [
  153, 152, 254, 57, 225, 179, 214, 215,
]

/**
 * Creates a _AddCollectionPolicy_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddCollectionPolicy
 * @category generated
 */
export function createAddCollectionPolicyInstruction(
  accounts: AddCollectionPolicyInstructionAccounts,
  args: AddCollectionPolicyInstructionArgs,
  programId = new web3.PublicKey('2HLsq8QGhRnUUwuukCKLNdpvNc4utW6AQVV1VoY9jgEd')
) {
  const [data] = addCollectionPolicyStruct.serialize({
    instructionDiscriminator: addCollectionPolicyInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.communityPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collection,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.collectionPolicy,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mainPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
