/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category LockCommunity
 * @category generated
 */
export type LockCommunityInstructionArgs = {
  communityIdx: number
}
/**
 * @category Instructions
 * @category LockCommunity
 * @category generated
 */
export const lockCommunityStruct = new beet.BeetArgsStruct<
  LockCommunityInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['communityIdx', beet.u32],
  ],
  'LockCommunityInstructionArgs'
)
/**
 * Accounts required by the _lockCommunity_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] communityPool
 * @property [_writable_] rewardVault
 * @property [_writable_] mainPool
 * @category Instructions
 * @category LockCommunity
 * @category generated
 */
export type LockCommunityInstructionAccounts = {
  admin: web3.PublicKey
  communityPool: web3.PublicKey
  rewardVault: web3.PublicKey
  mainPool: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const lockCommunityInstructionDiscriminator = [
  83, 86, 8, 247, 13, 177, 207, 96,
]

/**
 * Creates a _LockCommunity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category LockCommunity
 * @category generated
 */
export function createLockCommunityInstruction(
  accounts: LockCommunityInstructionAccounts,
  args: LockCommunityInstructionArgs,
  programId = new web3.PublicKey('2HLsq8QGhRnUUwuukCKLNdpvNc4utW6AQVV1VoY9jgEd')
) {
  const [data] = lockCommunityStruct.serialize({
    instructionDiscriminator: lockCommunityInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.communityPool,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.rewardVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mainPool,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
