/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link MainPool}
 * @category Accounts
 * @category generated
 */
export type MainPoolArgs = {
  superAdmin: web3.PublicKey
  totalCommunities: number
  totalUsers: number
  userCommunityAccountCreationFee: beet.bignum
  communityCreationFee: beet.bignum
  collectionAdditionFee: beet.bignum
  collectionPolicyAdditionFee: beet.bignum
  unstakeFee: beet.bignum
}

export const mainPoolDiscriminator = [198, 222, 117, 48, 134, 4, 64, 109]
/**
 * Holds the data for the {@link MainPool} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MainPool implements MainPoolArgs {
  private constructor(
    readonly superAdmin: web3.PublicKey,
    readonly totalCommunities: number,
    readonly totalUsers: number,
    readonly userCommunityAccountCreationFee: beet.bignum,
    readonly communityCreationFee: beet.bignum,
    readonly collectionAdditionFee: beet.bignum,
    readonly collectionPolicyAdditionFee: beet.bignum,
    readonly unstakeFee: beet.bignum
  ) {}

  /**
   * Creates a {@link MainPool} instance from the provided args.
   */
  static fromArgs(args: MainPoolArgs) {
    return new MainPool(
      args.superAdmin,
      args.totalCommunities,
      args.totalUsers,
      args.userCommunityAccountCreationFee,
      args.communityCreationFee,
      args.collectionAdditionFee,
      args.collectionPolicyAdditionFee,
      args.unstakeFee
    )
  }

  /**
   * Deserializes the {@link MainPool} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MainPool, number] {
    return MainPool.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MainPool} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MainPool> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find MainPool account at ${address}`)
    }
    return MainPool.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '2HLsq8QGhRnUUwuukCKLNdpvNc4utW6AQVV1VoY9jgEd'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, mainPoolBeet)
  }

  /**
   * Deserializes the {@link MainPool} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MainPool, number] {
    return mainPoolBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MainPool} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return mainPoolBeet.serialize({
      accountDiscriminator: mainPoolDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MainPool}
   */
  static get byteSize() {
    return mainPoolBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MainPool} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MainPool.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link MainPool} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === MainPool.byteSize
  }

  /**
   * Returns a readable version of {@link MainPool} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      superAdmin: this.superAdmin.toBase58(),
      totalCommunities: this.totalCommunities,
      totalUsers: this.totalUsers,
      userCommunityAccountCreationFee: (() => {
        const x = <{ toNumber: () => number }>(
          this.userCommunityAccountCreationFee
        )
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      communityCreationFee: (() => {
        const x = <{ toNumber: () => number }>this.communityCreationFee
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      collectionAdditionFee: (() => {
        const x = <{ toNumber: () => number }>this.collectionAdditionFee
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      collectionPolicyAdditionFee: (() => {
        const x = <{ toNumber: () => number }>this.collectionPolicyAdditionFee
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      unstakeFee: (() => {
        const x = <{ toNumber: () => number }>this.unstakeFee
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const mainPoolBeet = new beet.BeetStruct<
  MainPool,
  MainPoolArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['superAdmin', beetSolana.publicKey],
    ['totalCommunities', beet.u32],
    ['totalUsers', beet.u32],
    ['userCommunityAccountCreationFee', beet.u64],
    ['communityCreationFee', beet.u64],
    ['collectionAdditionFee', beet.u64],
    ['collectionPolicyAdditionFee', beet.u64],
    ['unstakeFee', beet.u64],
  ],
  MainPool.fromArgs,
  'MainPool'
)
