/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link NftTicket}
 * @category Accounts
 * @category generated
 */
export type NftTicketArgs = {
  mint: web3.PublicKey
  stakeTime: beet.bignum
  claimedTime: beet.bignum
  policy: web3.PublicKey
}

export const nftTicketDiscriminator = [236, 56, 134, 154, 218, 88, 207, 207]
/**
 * Holds the data for the {@link NftTicket} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class NftTicket implements NftTicketArgs {
  private constructor(
    readonly mint: web3.PublicKey,
    readonly stakeTime: beet.bignum,
    readonly claimedTime: beet.bignum,
    readonly policy: web3.PublicKey
  ) {}

  /**
   * Creates a {@link NftTicket} instance from the provided args.
   */
  static fromArgs(args: NftTicketArgs) {
    return new NftTicket(
      args.mint,
      args.stakeTime,
      args.claimedTime,
      args.policy
    )
  }

  /**
   * Deserializes the {@link NftTicket} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [NftTicket, number] {
    return NftTicket.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link NftTicket} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<NftTicket> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find NftTicket account at ${address}`)
    }
    return NftTicket.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '2HLsq8QGhRnUUwuukCKLNdpvNc4utW6AQVV1VoY9jgEd'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, nftTicketBeet)
  }

  /**
   * Deserializes the {@link NftTicket} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [NftTicket, number] {
    return nftTicketBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link NftTicket} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return nftTicketBeet.serialize({
      accountDiscriminator: nftTicketDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link NftTicket}
   */
  static get byteSize() {
    return nftTicketBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link NftTicket} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      NftTicket.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link NftTicket} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === NftTicket.byteSize
  }

  /**
   * Returns a readable version of {@link NftTicket} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      mint: this.mint.toBase58(),
      stakeTime: (() => {
        const x = <{ toNumber: () => number }>this.stakeTime
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      claimedTime: (() => {
        const x = <{ toNumber: () => number }>this.claimedTime
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      policy: this.policy.toBase58(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const nftTicketBeet = new beet.BeetStruct<
  NftTicket,
  NftTicketArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['mint', beetSolana.publicKey],
    ['stakeTime', beet.i64],
    ['claimedTime', beet.i64],
    ['policy', beetSolana.publicKey],
  ],
  NftTicket.fromArgs,
  'NftTicket'
)
