/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Taken}
 * @category Accounts
 * @category generated
 */
export type TakenArgs = {}

export const takenDiscriminator = [201, 151, 186, 48, 27, 54, 22, 224]
/**
 * Holds the data for the {@link Taken} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Taken implements TakenArgs {
  private constructor() {}

  /**
   * Creates a {@link Taken} instance from the provided args.
   */
  static fromArgs(args: TakenArgs) {
    return new Taken()
  }

  /**
   * Deserializes the {@link Taken} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Taken, number] {
    return Taken.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Taken} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Taken> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Taken account at ${address}`)
    }
    return Taken.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '2HLsq8QGhRnUUwuukCKLNdpvNc4utW6AQVV1VoY9jgEd'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, takenBeet)
  }

  /**
   * Deserializes the {@link Taken} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Taken, number] {
    return takenBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Taken} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return takenBeet.serialize({
      accountDiscriminator: takenDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Taken}
   */
  static get byteSize() {
    return takenBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Taken} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Taken.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Taken} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Taken.byteSize
  }

  /**
   * Returns a readable version of {@link Taken} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {}
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const takenBeet = new beet.BeetStruct<
  Taken,
  { accountDiscriminator: number[] /* size: 8 */ }
>(
  [['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  Taken.fromArgs,
  'Taken'
)
