/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link UserCommunityAccount}
 * @category Accounts
 * @category generated
 */
export type UserCommunityAccountArgs = {
  communityAddress: web3.PublicKey
  accumulatedReward: beet.bignum
  stakeCounter: number
  loanCounter: number
}

export const userCommunityAccountDiscriminator = [
  71, 113, 100, 103, 232, 126, 188, 13,
]
/**
 * Holds the data for the {@link UserCommunityAccount} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class UserCommunityAccount implements UserCommunityAccountArgs {
  private constructor(
    readonly communityAddress: web3.PublicKey,
    readonly accumulatedReward: beet.bignum,
    readonly stakeCounter: number,
    readonly loanCounter: number
  ) {}

  /**
   * Creates a {@link UserCommunityAccount} instance from the provided args.
   */
  static fromArgs(args: UserCommunityAccountArgs) {
    return new UserCommunityAccount(
      args.communityAddress,
      args.accumulatedReward,
      args.stakeCounter,
      args.loanCounter
    )
  }

  /**
   * Deserializes the {@link UserCommunityAccount} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [UserCommunityAccount, number] {
    return UserCommunityAccount.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link UserCommunityAccount} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<UserCommunityAccount> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find UserCommunityAccount account at ${address}`
      )
    }
    return UserCommunityAccount.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '2HLsq8QGhRnUUwuukCKLNdpvNc4utW6AQVV1VoY9jgEd'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, userCommunityAccountBeet)
  }

  /**
   * Deserializes the {@link UserCommunityAccount} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [UserCommunityAccount, number] {
    return userCommunityAccountBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link UserCommunityAccount} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return userCommunityAccountBeet.serialize({
      accountDiscriminator: userCommunityAccountDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link UserCommunityAccount}
   */
  static get byteSize() {
    return userCommunityAccountBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link UserCommunityAccount} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      UserCommunityAccount.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link UserCommunityAccount} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === UserCommunityAccount.byteSize
  }

  /**
   * Returns a readable version of {@link UserCommunityAccount} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      communityAddress: this.communityAddress.toBase58(),
      accumulatedReward: (() => {
        const x = <{ toNumber: () => number }>this.accumulatedReward
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      stakeCounter: this.stakeCounter,
      loanCounter: this.loanCounter,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const userCommunityAccountBeet = new beet.BeetStruct<
  UserCommunityAccount,
  UserCommunityAccountArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['communityAddress', beetSolana.publicKey],
    ['accumulatedReward', beet.u64],
    ['stakeCounter', beet.u32],
    ['loanCounter', beet.u32],
  ],
  UserCommunityAccount.fromArgs,
  'UserCommunityAccount'
)
